import { type FormEvent, useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import api from "../api/axios";
import type { CurrentUser } from "../types/auth";
import type { Product, ProductRequest } from "../types/product";

type FormState={name:string;category:"MOUSE"|"KEYBOARD"|"HEADSET";brand:string;price:string;stock:string;connectionType:"WIRED"|"WIRELESS"|"BOTH";imageUrl:string;description:string;weight:string;dpi:string;pollingRate:string;buttonCount:string;switchType:string;keyboardLayout:string;noiseLevel:string;responseTime:string;batteryHours:string;microphone:boolean};
const initial:FormState={name:"",category:"MOUSE",brand:"",price:"",stock:"",connectionType:"WIRELESS",imageUrl:"",description:"",weight:"",dpi:"",pollingRate:"",buttonCount:"",switchType:"",keyboardLayout:"",noiseLevel:"",responseTime:"",batteryHours:"",microphone:false};
const numberOrNull=(value:string)=>value===""?null:Number(value);

function AdminProductsPage(){
  const [authorized,setAuthorized]=useState<boolean|null>(null); const [products,setProducts]=useState<Product[]>([]); const [form,setForm]=useState<FormState>(initial); const [editingId,setEditingId]=useState<number|null>(null); const [message,setMessage]=useState(""); const token=localStorage.getItem("accessToken");
  const loadProducts=()=>api.get<Product[]>("/api/products").then((r)=>setProducts(r.data));
  useEffect(()=>{if(!token){setAuthorized(false);return;} api.get<CurrentUser>("/api/users/me").then((r)=>{setAuthorized(r.data.role==="ADMIN");if(r.data.role==="ADMIN")void loadProducts();}).catch(()=>setAuthorized(false));},[token]);
  if(!token)return <Navigate to="/login" replace/>; if(authorized===false)return <Navigate to="/" replace/>; if(authorized===null)return <p className="state-message">관리자 권한을 확인하는 중입니다...</p>;
  const payload=():ProductRequest=>({name:form.name,category:form.category,brand:form.brand,price:Number(form.price),stock:Number(form.stock),connectionType:form.connectionType,imageUrl:form.imageUrl||null,description:form.description,spec:{weight:numberOrNull(form.weight),dpi:numberOrNull(form.dpi),pollingRate:numberOrNull(form.pollingRate),buttonCount:numberOrNull(form.buttonCount),switchType:form.switchType||null,keyboardLayout:form.keyboardLayout||null,noiseLevel:numberOrNull(form.noiseLevel),responseTime:numberOrNull(form.responseTime),batteryHours:numberOrNull(form.batteryHours),microphone:form.category==="HEADSET"?form.microphone:null}});
  const submit=async(e:FormEvent)=>{e.preventDefault();setMessage("");try{if(editingId)await api.put(`/api/admin/products/${editingId}`,payload());else await api.post("/api/admin/products",payload());setForm(initial);setEditingId(null);setMessage(editingId?"상품을 수정했습니다.":"상품을 등록했습니다.");await loadProducts();}catch{setMessage("저장하지 못했습니다. 필수값과 관리자 권한을 확인해 주세요.");}};
  const edit=(p:Product)=>{setEditingId(p.id);setForm({name:p.name,category:p.category as FormState["category"],brand:p.brand??"",price:String(p.price),stock:String(p.stock),connectionType:(p.connectionType??"WIRELESS") as FormState["connectionType"],imageUrl:p.imageUrl??"",description:p.description??"",weight:String(p.spec?.weight??""),dpi:String(p.spec?.dpi??""),pollingRate:String(p.spec?.pollingRate??""),buttonCount:String(p.spec?.buttonCount??""),switchType:p.spec?.switchType??"",keyboardLayout:p.spec?.keyboardLayout??"",noiseLevel:String(p.spec?.noiseLevel??""),responseTime:String(p.spec?.responseTime??""),batteryHours:String(p.spec?.batteryHours??""),microphone:p.spec?.microphone??false});window.scrollTo({top:0,behavior:"smooth"});};
  const remove=async(p:Product)=>{if(!confirm(`${p.name} 상품을 삭제할까요?`))return;try{await api.delete(`/api/admin/products/${p.id}`);await loadProducts();}catch{setMessage("상품을 삭제하지 못했습니다.");}};
  const field=(key:keyof FormState,value:string|boolean)=>setForm({...form,[key]:value});
  return <section className="page-container admin-page"><div className="page-title"><span className="eyebrow">ADMIN CONSOLE</span><h1>상품 관리</h1><p>상품과 추천에 사용할 세부 사양을 관리합니다.</p></div><div className="admin-layout"><form className="product-form" onSubmit={submit}><h2>{editingId?"상품 수정":"새 상품 등록"}</h2><div className="form-grid"><label>상품명<input value={form.name} onChange={e=>field("name",e.target.value)} required/></label><label>브랜드<input value={form.brand} onChange={e=>field("brand",e.target.value)}/></label><label>카테고리<select value={form.category} onChange={e=>field("category",e.target.value)}><option value="MOUSE">마우스</option><option value="KEYBOARD">키보드</option><option value="HEADSET">헤드셋</option></select></label><label>연결 방식<select value={form.connectionType} onChange={e=>field("connectionType",e.target.value)}><option value="WIRED">유선</option><option value="WIRELESS">무선</option><option value="BOTH">유·무선</option></select></label><label>가격<input type="number" min="0" value={form.price} onChange={e=>field("price",e.target.value)} required/></label><label>재고<input type="number" min="0" value={form.stock} onChange={e=>field("stock",e.target.value)} required/></label><label className="wide">이미지 URL<input value={form.imageUrl} onChange={e=>field("imageUrl",e.target.value)}/></label><label className="wide">상품 설명<textarea value={form.description} onChange={e=>field("description",e.target.value)}/></label></div><h3>상품 사양</h3><div className="form-grid compact">{([['weight','무게(g)'],['dpi','DPI'],['pollingRate','폴링레이트'],['buttonCount','버튼 수'],['noiseLevel','소음 수치'],['responseTime','응답속도'],['batteryHours','배터리 시간']] as [keyof FormState,string][]).map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={String(form[key])} onChange={e=>field(key,e.target.value)}/></label>)}<label>스위치<input value={form.switchType} onChange={e=>field("switchType",e.target.value)}/></label><label>키보드 배열<input value={form.keyboardLayout} onChange={e=>field("keyboardLayout",e.target.value)}/></label></div>{message&&<p className={message.includes("못")?"form-message error":"form-message success"}>{message}</p>}<div className="form-buttons"><button className="admin-submit" type="submit">{editingId?"수정 저장":"상품 등록"}</button>{editingId&&<button className="cancel-button" type="button" onClick={()=>{setEditingId(null);setForm(initial);}}>취소</button>}</div></form><div className="admin-list"><h2>등록 상품 <b>{products.length}</b></h2>{products.map(p=><article key={p.id}><div><small>{p.category} · {p.brand}</small><h3>{p.name}</h3><span>{p.price.toLocaleString("ko-KR")}원 · 재고 {p.stock}</span></div><div><button onClick={()=>edit(p)}>수정</button><button className="danger" onClick={()=>void remove(p)}>삭제</button></div></article>)}</div></div></section>;
}

export default AdminProductsPage;
