spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/gamegearmatch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gamegear
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
